..

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -582,16 +582,16 @@ jobs:
       - run:
           name: Frontend smoke test.
           command: |
-            # URL="http://uda-fp23.s3-website-us-east-1.amazonaws.com/#/employees"            
-            # echo ${URL} 
-            # if curl -s ${URL} | grep "Welcome"
-            # then
-            #   echo "Frontend is working successfully"
-            #     # Change this to 0 after the job fails
-            #   exit 0
-            # else
-            #   exit 1
-            # fi
+            URL="http://uda-fp23.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+              echo "Frontend is working successfully"
+                # Change this to 0 after the job fails
+              exit 0
+            else
+              exit 1
+            fi
 
 
       
