..

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -322,74 +322,74 @@ jobs:
 
   
 
-  deploy-frontend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout 
-      - add_ssh_keys:
+  # deploy-frontend:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout 
+  #     - add_ssh_keys:
               
-          fingerprints: 
+  #         fingerprints: 
             
-            - "55:f3:3d:67:45:24:b3:9f:b8:17:3f:c4:75:fd:e2:07"
+  #           - "55:f3:3d:67:45:24:b3:9f:b8:17:3f:c4:75:fd:e2:07"
       
-      - run:
-          name: Install awscli
-          command: |
-            sudo apt install -y tar gzip
-            echo "installing AWS CLI "
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
+  #     - run:
+  #         name: Install awscli
+  #         command: |
+  #           sudo apt install -y tar gzip
+  #           echo "installing AWS CLI "
+  #           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+  #           unzip awscliv2.zip
+  #           sudo ./aws/install
 
-      - run:
-          name: Install Ansible
-          command: |
+  #     - run:
+  #         name: Install Ansible
+  #         command: |
             
-            sudo apt install ansible 
+  #           sudo apt install ansible 
 
-      - run:
-          name: Install Python
-          command: |
-            echo "installing pyton3"
-            sudo apt install python3
+  #     - run:
+  #         name: Install Python
+  #         command: |
+  #           echo "installing pyton3"
+  #           sudo apt install python3
           
-      - run: ansible --version
+  #     - run: ansible --version
 
-      - restore_cache:
-          keys: 
-            - frontend-build  
+  #     - restore_cache:
+  #         keys: 
+  #           - frontend-build  
       
-      - attach_workspace:
-          at: ~/project/inv
+  #     - attach_workspace:
+  #         at: ~/project/inv
     
-      - run: cat ~/project/inv/inventory.txt
-      - run:
-          name: Get backend url
-          command: |
+  #     - run: cat ~/project/inv/inventory.txt
+  #     - run:
+  #         name: Get backend url
+  #         command: |
             
-            export BACKEND_IP=$(aws ec2 describe-instances    --query 'Reservations[*].Instances[*].PublicIpAddress'   --filters "Name=tag:Name,Values=Uda"    --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "API_URL = ${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
+  #           export BACKEND_IP=$(aws ec2 describe-instances    --query 'Reservations[*].Instances[*].PublicIpAddress'   --filters "Name=tag:Name,Values=Uda"    --output text)
+  #           export API_URL="http://${BACKEND_IP}:3030"
+  #           echo "API_URL = ${API_URL}"
+  #           echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+  #           cat frontend/.env
 
 
-      - run:
-          name: Deploy frontend objects
-          command: |
-            cd /home/circleci/project/frontend
-            npm install
-            npm run build
-            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:5}".tar.gz dist
-            aws s3 cp dist s3://uda-fp23 --recursive
+  #     - run:
+  #         name: Deploy frontend objects
+  #         command: |
+  #           cd /home/circleci/project/frontend
+  #           npm install
+  #           npm run build
+  #           tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:5}".tar.gz dist
+  #           aws s3 cp dist s3://uda-fp23 --recursive
 
 
-      - destroy_environment_backend
+  #     - destroy_environment_backend
 
-      - revert-migrations
+  #     - revert-migrations
 
-      - destroy_environment_frontend
+  #     - destroy_environment_frontend
 
   
 
@@ -398,7 +398,7 @@ jobs:
 
   deploy-backend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/base:stable
     steps:
       - checkout 
       - add_ssh_keys:
@@ -412,14 +412,22 @@ jobs:
           name: Install dependencies
           command: |
             
-            
+            # install AWS CLI
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install
 
-            # Ansible 
-            
-            sudo apt install ansible 
+            # install Ansible
+            sudo apt update
+            sudo apt install software-properties-common -y
+            sudo add-apt-repository --yes --update ppa:ansible/ansible
+            sudo apt install ansible -y    
+
+            # install node js
+            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
+            sudo apt install -y nodejs
+            sudo npm install --global n
+            sudo n 13.8.0
 
             
       - run: ansible --version 
@@ -435,11 +443,11 @@ jobs:
       - run:
           name: packging backend
           command: |
-            cd backend
+            cd  ~/backend
             npm install
             npm run build
             tar -czf artifact.tar.gz dist/* package*
-            cd ..
+            cd ~/
             cp backend/artifact.tar.gz  roles/deploy/files
 
       - run:
@@ -452,13 +460,13 @@ jobs:
 
 
 
-              cd ~/project/backend
-              npm i
-              npm run build
-              cd ..
-              pwd
-              # Zip the directory
-              tar -C backend -czvf artifact.tar.gz .
+              # cd ~/project/backend
+              # npm i
+              # npm run build
+              # cd ..
+              # pwd
+              # # Zip the directory
+              # tar -C backend -czvf artifact.tar.gz .
               
               echo "Contents  of the inventory.txt file is -------"
               cat ~/project/inv/inventory.txt
@@ -470,13 +478,13 @@ jobs:
       - run:
           name: install pm2 
           command: |
-              sudo npm i -g pm2
+              #sudo npm i -g pm2
 
       - run:
           name: Deploy backend
           command: |
                 npm install
-                #pm2 stop default
+                pm2 stop default
                 pm2 start npm -- start
 
 
@@ -526,16 +534,16 @@ jobs:
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://uda-fp23.s3-website-us-east-1.amazonaws.com/#/employees"            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
-            then
-              echo "Frontend is working successfully"
-                # Change this to 0 after the job fails
-              exit 0
-            else
-              exit 1
-            fi
+            # URL="http://uda-fp23.s3-website-us-east-1.amazonaws.com/#/employees"            
+            # echo ${URL} 
+            # if curl -s ${URL} | grep "Welcome"
+            # then
+            #   echo "Frontend is working successfully"
+            #     # Change this to 0 after the job fails
+            #   exit 0
+            # else
+            #   exit 1
+            # fi
 
 
       
